server:
  undertow:
    worker-threads: 50
    io-threads: 2
  port: 8100
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/plain,application/x-javascript,text/css,application/xml
    min-response-size: 4096
spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      # 配置采集率1.0表示100%，0.1表示10%
      probability: ${SAMPLER_PROBABILITY:1.0}
  application:
    name: demo1-service
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  zipkin:
    # 配置zipkin服务地址
    base-url: ${ZIPKIN:http://10.96.0.13:9411/}
  jackson:
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  logPath: /var/log/${spring.application.name}
  level:
    org:
      springframework: info
    com:
      netflix:
        discovery:
          shared:
            resolver:
              aws: error
      alibaba:
        nacos:
          client:
            naming: error



management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

ribbon:
  # ribbon缓存时间
  ServerListRefreshInterval: 2000
  ReadTimeout: 30000
  ConnectTimeout: 30000
  # 是否所有操作都重试
  OkToRetryOnAllOperations: true
  # 重试负载均衡其他的实例最大重试次数,不包括首次server
  MaxAutoRetriesNextServer: 2
  # 同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 1
